spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j133_spring_car?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update